---

- name: install apaache server

  hosts: [db] 
  become: yes

  tasks:
  - name: install apache2 server
    apt: name=apache2 state=present
 
  - name: service must be running        
    service: name=apache2 state=started

