---

- name: install apache2 & php & mysqlserver
  hosts: [db]
  become: true
  become_user: root
  gather_facts: true

  tasks:
  - name: install LAMP package with help of with
    package: name={{item}} state=present
    with_items:
     - apache2
     - libapache2-mod-php5
     - php-cli
     - php-mcrypt
     - php-gd
     - php-mysql
     - mysql-server

